#!/usr/bin/env python
from __future__ import division

import sys
from metasane.core import MetadataTable, VocabularySet

if len(sys.argv) != 3:
    sys.stderr.write("Usage: metasane <metadata filepath> "
                     "<controlled vocabularies directory>\n")
    sys.exit(1)

md_fp, vocab_dir = sys.argv[1:]
md_table = MetadataTable.fromFile(md_fp)
vocabs = VocabularySet(vocab_dir)

controlled_fields = md_table.candidateControlledFields(vocabs)
validation_results = md_table.validateControlledFields(vocabs)

print "The following fields appear to reference controlled vocabularies:\n"
for field, vocab_matches in controlled_fields.items():
    print "%s\t%s" % (field, list(vocab_matches)[0])
print

print("The following values do not match the fields' controlled vocabularies "
      "(case-insensitive matching was used):\n")
for field, invalid_values in validation_results.items():
    print "%s\t%s" % (field, ', '.join(list(invalid_values)))
